// Blue Slime tem que fzer aqui!!
// Blue Slime tem que fzer aqui!!
// Blue Slime tem que fzer aqui!!
// Blue Slime tem que fzer aqui!!
// Blue Slime tem que fzer aqui!!
// Blue Slime tem que fzer aqui!!
// Blue Slime tem que fzer aqui!!
// Blue Slime tem que fzer aqui!!
// Blue Slime tem que fzer aqui!!
// Blue Slime tem que fzer aqui!!
// Blue Slime tem que fzer aqui!!
// Blue Slime tem que fzer aqui!!
// Blue Slime tem que fzer aqui!!
// Blue Slime tem que fzer aqui!!
// Blue Slime tem que fzer aqui!!
// Blue Slime tem que fzer aqui!!
// Blue Slime tem que fzer aqui!!
// Blue Slime tem que fzer aqui!!
// Blue Slime tem que fzer aqui!!
// Blue Slime tem que fzer aqui!!
// Blue Slime tem que fzer aqui!!
// Blue Slime tem que fzer aqui!!
// Blue Slime tem que fzer aqui!!
// Blue Slime tem que fzer aqui!!
// Blue Slime tem que fzer aqui!!
